# fly.toml app configuration file generated for simata-rfid-demo on 2024-02-18T23:55:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simata-rfid-demo'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
